name: Render CV
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  render-paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: typst-community/setup-typst@v5
      - run: typst compile CV.typ CV-mts.pdf
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: CV-mts.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}